import { Inter } from "next/font/google";

import "./globals.css";
import { Provider } from "./provider";
import Navbar from "./components/Layout/Navbar";
import Footer from "./components/Layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta charset="utf-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width" />
      <meta name="robots" content="index, follow" />

      <meta
        name="csrf-token"
        content="KgvbWDJZDDwud524LbE5WM5ynJwTQuhfyLSb8unR"
      />
      <title>YarnLink Global Corporation</title>
      <meta name="keywords" content="YarnLink Global Corporation" />
      <meta name="description" content="YarnLink Global Corporation" />
      <link rel="shortcut icon" href="/assets/img/favicon.png" />
      <link rel="canonical" href="index.html" />

      <link href="/assets/css/app.css" rel="stylesheet" />
      <link
        rel="stylesheet"
        href="/assets/css/responsive.css"
        type="text/css"
      />

      <link
        rel="stylesheet"
        href="/assets/font-awesome/css/font-awesome.min.css"
        type="text/css"
      />

      <link rel="stylesheet" href="/assets/css/select2.css" type="text/css" />
      <link
        rel="stylesheet"
        href="/assets/css/select2-bs4.css"
        type="text/css"
      />
      <script type="text/javascript" src="/assets/js/select2.js" async></script>

      <link
        rel="stylesheet"
        href="/assets/datepicker/datepicker.css"
        type="text/css"
      />

      <link
        rel="stylesheet"
        href="/assets/simplebar/simplebar.css"
        type="text/css"
      />

      <link
        rel="stylesheet"
        href="/assets/swipper/swipper.css"
        type="text/css"
      />
      <link href="/assets/css/front-style.css" rel="stylesheet" />
      <body className={inter.className}>
        <Navbar />
        <Provider>{children}</Provider>
        <Footer />
      </body>
    </html>
  );
}
